"""NTU RGB+D 60 action class labels (0-indexed)."""

NTU60_ACTIONS: list[str] = [
    "drink water",
    "eat meal/snack",
    "brushing teeth",
    "brushing hair",
    "drop",
    "pickup",
    "throw",
    "sitting down",
    "standing up",
    "clapping",
    "reading",
    "writing",
    "tear up paper",
    "wear jacket",
    "take off jacket",
    "wear a shoe",
    "take off a shoe",
    "wear on glasses",
    "take off glasses",
    "put on a hat/cap",
    "take off a hat/cap",
    "cheer up",
    "hand waving",
    "kicking something",
    "reach into pocket",
    "hopping",
    "jump up",
    "make a phone call",
    "playing with phone",
    "typing on keyboard",
    "pointing to something",
    "taking a selfie",
    "check time (watch)",
    "rub two hands together",
    "nod head/bow",
    "shake head",
    "wipe face",
    "salute",
    "put palms together",
    "cross hands in front",
    "sneeze/cough",
    "staggering",
    "falling",
    "touch head",
    "touch chest",
    "touch back",
    "touch neck",
    "nausea/vomiting",
    "use a fan",
    "punching/slapping",
    "kicking other person",
    "pushing other person",
    "pat on back",
    "point finger at person",
    "hugging",
    "giving something",
    "touch pocket",
    "handshaking",
    "walking towards",
    "walking apart",
]
